### ISSUE TITLE
Code generation with maven plugin does not work for yaml files

### ISSUE THREAD

**Issue by nabcos** [zalando-stups/swagger-codegen-tooling#19]
When configuring a yaml file, the swagger parser tries to interpret it as json. The configuration `yamlToJson` apparently converts a swagger definition from yaml to json file, but the resulting file is not used for the code generation step.

Plugin configuration:
~~~xml
            <plugin>
                <groupId>org.zalando.maven.plugins</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>0.4.15</version>
                <configuration>
                    <apiFile>${project.basedir}/src/main/swagger/swagger.yaml</apiFile>
                    <yamlToJson>true</yamlToJson>
                    <language>jaxrsinterfaces</language>
                    <apiPackage>de.zalando.phrs.coupon.api</apiPackage>
                    <modelPackage>de.zalando.phrs.coupon.model</modelPackage>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.zalando.stups</groupId>
                        <artifactId>swagger-codegen-template-jaxrs-interfaces</artifactId>
                        <version>0.4.15</version>
                    </dependency>
                </dependencies>
            </plugin>
~~~

Console output:
~~~
reading from /home/hanzelm/git/phrasers/coupon-api/coupon-service/core/src/main/swagger/swagger.yaml
(was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["discount"]) (through reference chain: io.swagger.models.parameters.BodyParameter["schema"]) (through reference chain: io.swagger.models.Path["post"]->io.swagger.models.Operation["parameters"]->java.util.ArrayList[0]) (through reference chain: io.swagger.models.Swagger["paths"]->java.util.LinkedHashMap["/coupons"])
reading from /home/hanzelm/git/phrasers/coupon-api/coupon-service/core/src/main/swagger/swagger.yaml
(was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["discount"]) (through reference chain: io.swagger.models.parameters.BodyParameter["schema"]) (through reference chain: io.swagger.models.Path["post"]->io.swagger.models.Operation["parameters"]->java.util.ArrayList[0]) (through reference chain: io.swagger.models.Swagger["paths"]->java.util.LinkedHashMap["/coupons"])
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')
 at [Source: /home/hanzelm/git/phrasers/coupon-api/coupon-service/core/src/main/swagger/swagger.yaml; line: 1, column: 9]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3201)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2360)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8Sreading from /home/hanzelm/git/phrasers/coupon-api/coupon-service/core/src/main/swagger/swagger.yaml
(was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["discount"]) (through reference chain: io.swagger.models.parameters.BodyParameter["schema"]) (through reference chain: io.swagger.models.Path["post"]->io.swagger.models.Operation["parameters"]->java.util.ArrayList[0]) (through reference chain: io.swagger.models.Swagger["paths"]->java.util.LinkedHashMap["/coupons"])
reading from /home/hanzelm/git/phrasers/coupon-api/coupon-service/core/src/main/swagger/swagger.yaml
(was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["discount"]) (through reference chain: io.swagger.models.parameters.BodyParameter["schema"]) (through reference chain: io.swagger.models.Path["post"]->io.swagger.models.Operation["parameters"]->java.util.ArrayList[0]) (through reference chain: io.swagger.models.Swagger["paths"]->java.util.LinkedHashMap["/coupons"])
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')
 at [Source: /home/hanzelm/git/phrasers/coupon-api/coupon-service/core/src/main/swagger/swagger.yaml; line: 1, column: 9]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3201)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2360)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:147)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:82)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:36)
	at org.zalando.stups.swagger.codegen.StandaloneCodegenerator.generate(StandaloneCodegenerator.java:130)
	at org.zalando.maven.plugins.swagger.codegen.CodegenMojo.execute(CodegenMojo.java:100)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)treamJsonParser.java:690)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:147)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:82)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:36)
	at org.zalando.stups.swagger.codegen.StandaloneCodegenerator.generate(StandaloneCodegenerator.java:130)
	at org.zalando.maven.plugins.swagger.codegen.CodegenMojo.execute(CodegenMojo.java:100)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
~~~

**Comment by jbellmann** [comment]
Hi Benjamin,

I'm not quite sure that this problem is on our side. All our test are running fine. So without your complete definition-yaml-file I'm not able to find an issue.

But for easier testing of everything related to 'swagger-codegen-tooling' (generator, maven-plugin, codegen-ui-controller) I created an example-project [here](https://github.com/zalando-stups/swagger-codegen-tooling-app). Please follow the README and let me know about your progress.

**Comment by nabcos** [comment]
Yes, it's actually an issue in the swagger parser. Yaml is parsed, but the model is apparently invalid, even though swagger-api/validator-badge is saying there are no problems. The problems are actually  printed via stdout (the two NPEs just above the stack trace), but the unusual behavior to "just try it as json if it failed as yaml" and the resulting stack trace just drowned out everything else for me. Sorry for the noise.

**Comment by sleroy** [comment]
Indeed this behaviour is really annoying :-/ and the lack of debug output
