### ISSUE TITLE
Builder Pattern for generated models

### ISSUE THREAD

**Issue by tknerr** [zalando-stups/swagger-codegen-tooling#7]
It would be awesome (and low hanging fruit probably ;-)) if the generated models could be contructed via Builder pattern, e.g. `BlogPost p = new BlogPostBuilder().title("foo").content("bar").author("baz").build();`

What do you think?

**Comment by jbellmann** [comment]
Nice idea, can you send me an 'template-example' for 'BlogPost'?

**Comment by tknerr** [comment]
BlogPost was just a fictionary example ;-)

But it could look like this, e.g. in `swagger.yml`:
```yaml
definitions:
  BlogPost:
    properties:
      title:
        type: string
      content:
        type: string
      author:
        type: string
```

And the generated `BlogPost.java`:
```java
package foo.bar.rest.model;


import io.swagger.annotations.*;
import com.fasterxml.jackson.annotation.JsonProperty;


@ApiModel(description = "")
public class BlogPost  {
  
  private String title = null;
  private String content = null;
  private String author = null;

  
  /**
   **/
  @ApiModelProperty(value = "")
  @JsonProperty("title")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  
  /**
   **/
  @ApiModelProperty(value = "")
  @JsonProperty("content")
  public String getContent() {
    return content;
  }
  public void setContent(String content) {
    this.content = content;
  }

  
  /**
   **/
  @ApiModelProperty(value = "")
  @JsonProperty("author")
  public String getAuthor() {
    return author;
  }
  public void setAuthor(String author) {
    this.author = author;
  }

  

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlogPost {\n");
    
    sb.append("  title: ").append(title).append("\n");
    sb.append("  content: ").append(content).append("\n");
    sb.append("  author: ").append(author).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
```

And besides that a `BlogPostBuilder.java` (exemplary):
```java
package foo.bar.rest.model;

public class BlogPostBuilder {
    private BlogPost blogPost;

    public BlogPostBuilder() {
        blogPost = new BlogPost();
    }

    public BlogPostBuilder title(String title) {
        blogPost.setTitle(title);
        return this;
    }

    public BlogPostBuilder content(String content) {
        blogPost.setContent(content);
        return this;
    }

    public BlogPostBuilder author(String author) {
        blogPost.setAuthor(author);
        return this;
    }
    
    public BlogPost build() {
        return blogPost;
    }
}
```

**Comment by jbellmann** [comment]
Thank you, I will try to get this working in the next days.

**Comment by jbellmann** [comment]
It's implemented. Please have a look and try out. Use <enableBuilderSupport>true</enabledBuilderSupport> [in the pom](https://github.com/zalando-stups/swagger-codegen-tooling/blob/master/swagger-codegen-maven-plugin/src/it/kio-yaml-with-Builder/pom.xml).

**Comment by tknerr** [comment]
Hi @jbellmann, thanks for implementing this!

Unfortunately, starting with 0.48 I can't use the plugin anymore. I suspect the compiled class files are not backwards compatible with Java 7 anymore.

Here's what I get:
```
Jul 01, 2015 9:58:39 AM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: org.zalando.maven.plugins.swagger.codegen.CodegenMojo
java.lang.TypeNotPresentException: Type org.zalando.maven.plugins.swagger.codegen.CodegenMojo not present
        at org.sonatype.guice.bean.reflect.URLClassSpace.loadClass(URLClassSpace.java:109)
        at org.sonatype.guice.bean.reflect.NamedClass.load(NamedClass.java:45)
        at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
        at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
        at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
        at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
		at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.UnsupportedClassVersionError: org/zalando/maven/plugins/swagger/codegen/CodegenMojo : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:386)
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
        at org.sonatype.guice.bean.reflect.URLClassSpace.loadClass(URLClassSpace.java:101)
        ... 41 more

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.397s
[INFO] Finished at: Wed Jul 01 09:58:39 CEST 2015
[INFO] Final Memory: 32M/449M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.zalando.maven.plugins:swagger-codegen-maven-plugin:0.4.8:codegen (generate-jaxrs-interfaces) on project aua-core-sl-rest-api: Execution generate-jaxrs-interfaces of goal org.zalando.maven.plugins:swagger-codegen-maven-plugin:0.4.8:codegen failed: Unable to load the mojo 'codegen' in the plugin 'org.zalando.maven.plugins:swagger-codegen-maven-plugin:0.4.8' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/zalando/maven/plugins/swagger/codegen/CodegenMojo : Unsupported major.minor version 52.0
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.zalando.maven.plugins:swagger-codegen-maven-plugin:0.4.8
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
....
```

**Comment by jbellmann** [comment]
Thanks for the input. I will check and release an new version.
Sorry for that.

**Comment by jbellmann** [comment]
Sorry again. I updated to a new version of parent-pom and dropped some configurations without eyes on java-version.

0.4.10 is a rebuild of 0.4.9 with java 1.7 set. Should be available on Maven-Central.

Let me know if you have more issues with the release or that it works for you.

**Comment by tknerr** [comment]
@jbellmann thanks for re-releasing! The plugin is working again now with our Java version, but the builders were not created.

The log files tell me that it's not supported for the "jaxrsinterfaces" generator:
```
...
[INFO] Generate for language : jaxrsinterfaces
[INFO] BuilderSupport enabled ...
[INFO] but not supported by : jaxrsinterfaces
...
```

Is that by intent or did I configure something wrong?

Here's the relevant pom fragment:
```xml
  <plugin>
                <groupId>org.zalando.maven.plugins</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>0.4.10</version>
                <executions>
                    <execution>
                        <id>generate-jaxrs-interfaces</id>
                        <goals>
                            <goal>codegen</goal>
                        </goals>
                        <configuration>
                            <language>jaxrsinterfaces</language>
                            <apiFile>${project.basedir}/src/main/resources/swagger.yaml</apiFile>
                            <apiPackage>foo.bar.rest.api</apiPackage>
                            <modelPackage>foo.bar.rest.model</modelPackage>
                            <outputDirectory>${generated-jaxrs-sources}</outputDirectory>
                            <enableBuilderSupport>true</enableBuilderSupport>
                            <!-- generate .json as well -->
                            <yamlToJson>true</yamlToJson>
                            <yamlToJsonOutputDirectory>${extracted-swaggerui-sources}</yamlToJsonOutputDirectory>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.zalando.stups</groupId>
                        <artifactId>swagger-codegen-template-jaxrs-interfaces</artifactId>
                        <version>0.4.10</version>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by jbellmann** [comment]
Hi, I have to sorry again. But as 'Spring-Fanboy' I was to focused to get this to work with the spring-generators. But 0.4.11 is available in 'Maven-Central' and I also added an [integration-test](https://github.com/zalando-stups/swagger-codegen-tooling/tree/master/swagger-codegen-maven-plugin/src/it/kio-yaml-jaxrs-with-Builder) to make sure that the expected 'Builders' will be generated. Your pom.xml-snippet looks good to me. [JSR 303 support](https://github.com/zalando-stups/swagger-codegen-tooling/issues/5) is not implemented in 'jaxrsinterfaces' only in the spring-generators so far.

Many thanks for your feedback and the time you invested so far to try out the project. Maybe we need some more releases until we get everything working. :-)

**Comment by SunriseJJJ** [comment]
Hi!
Thanks for enabling Java 1.7 again! I can now use your plugin again.

So, after enabling builders, now i see that for entity like this:
```
"accountDetails": {
    "type": "object",
    "properties": {
        "systemId": {
            "type": "string",
        },
        "clientId": {
            "type": "string",
        },
        "accountType": {
            "type": "string",
            "enum": [
                "Single",
                "Joint"
            ],
        }
    }
}
```

builder was not generated correctly. builder neither contains this enum nor tries to import this (i can understand why, because this enum now can be generated only as inline enum [and even not in one place] by swagger-codegen, i talking with swagger-codegen devs in topic https://github.com/swagger-api/swagger-codegen/issues/315).
so with this issue code can not even compile. if codegen devs add this feature - i think second option can be implemented.
As temporary solution, i may recommend to add this enum also to builder or try to import enum from parent entity (accountDetails in example)

**Comment by jbellmann** [comment]
@SunriseJJJ just a question before we go to the issue. Did 'skip-Api' work for you?

Thanks for reporting. Can you please provide an very simple 'yaml'-file where the same is configured as in json above? And it maybe helps me to find out what is going wrong when you also provide the wrong generated code. That would be very helpful.

I will also try to find a more simple but complete example for generating correct model and builders.

**Comment by jbellmann** [comment]
@SunriseJJJ I released a new version 0.4.12 where I just generate an '*'-import for the model into the builder. For your example above that would be 'import pkg.AccountDetails.*;' . That should fix the problem. At least for the [simple test](https://github.com/zalando-stups/swagger-codegen-tooling/blob/master/swagger-codegen-templates/swagger-codegen-template-spring-interfaces/src/test/java/de/zalando/stups/swagger/codegen/language/SpringInterfacesGeneratorTest.java#L43) it did.

So, please try out version 0.4.12 and let me know how it works for you (or not work ;-) ).

Have a nice weekend.

**Comment by tknerr** [comment]
@jbellmann you fixed it before I could report it ;-)

Works great for me, thanks!!!

Imho we can close this . @SunriseJJJ works for you, too?

**Comment by jbellmann** [comment]
@tknerr 

Seems @SunriseJJJ is not answering anymore. If you are happy with the implementation please close this issue.

Thanks for your support.

**Comment by tknerr** [comment]
:+1: thanks @jbellmann !

**Comment by SunriseJJJ** [comment]
@jbellmann Hi again! sorry, my bad.
Builders work very well, thanks!
